services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    command: -p ${POSTGRES_PORT}

  rabbitmq:
    image: rabbitmq:3
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${AMQP_NODE_PORT}:${AMQP_NODE_PORT}
    environment:
      - RABBITMQ_NODE_PORT=${AMQP_NODE_PORT}
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia
